Generate keys with metadata
SSH-key-rotation-AWS/team-henrique pull request #68
Opened 2023-07-05 23:10 UTC by ygins

- Added KeyMetadata class with created_by and time_created fields
 - Added methods to the publishers to publish metadata
 - Started migrating some code to PathLib, still a WIP
 - Added tests for S3 publisher and metadata

2023-07-05 23:11 UTC, ygins commented
closes #58 
closes #51

2023-07-06 14:54 UTC, yydiamen approved these changes

2023-07-06 15:00 UTC, merged

2023-07-06 15:01 UTC, thehcma requested changes

2023-07-06 15:01 UTC, thehcma commented on switcheroo/server/retrieve_public_keys.py
>      if not os.path.isdir(key_dir):
I feel like I reviewed this already and we didn't act on the review - so here it goes again - don't test and act - rather act and handle the exception

also use `pathlib`

2023-07-06 15:01 UTC, thehcma commented on switcheroo/server/retrieve_public_keys.py
>      s3_client = boto3.client("s3")
this should be done via the datastore (using AWS should be done only when the AWS S3 data store is in use)

2023-07-06 15:50 UTC, ygins commented on switcheroo/custom_keygen.py
> +        with open(private_key_path, "wb") as private_out:
pathlib.Path.mkdir takes a mode - can we do that instead?

2023-07-06 16:04 UTC, thehcma commented on switcheroo/custom_keygen.py
> +        with open(private_key_path, "wb") as private_out:
`mkdir` creates a directory - you need to create the file with the proper permissions as well